; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = devkit_v2
src_dir = einkPDA_V2

[extra]
baud = 115200

[env]
monitor_speed = ${extra.baud}

[env:devkit_v2]
platform = espressif32
build_flags= -DBOARD_HAS_PSRAM
framework = arduino
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi 
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
monitor_filters = esp32_exception_decoder
lib_deps = 
    adafruit/Adafruit GFX Library@^1.12.0
    adafruit/Adafruit TCA8418@^1.0.2
    adafruit/RTClib@^2.1.4
    olikraus/U8g2@^2.36.4
    https://github.com/bildr-org/MPR121
    ; Currently using a fork of the library
    ; zinggjm/GxEPD2@^1.6.3
    https://github.com/ashtf8/GxEPD2_Editable_useFastFullUpdate

