; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
src_dir = einkPDA_V2
default_envs = devkit

[extra]
baud = 115200

[env]
platform = espressif32
framework = arduino
; monitor_speed = ${extra.baud}
lib_deps = 
    adafruit/Adafruit GFX Library@^1.12.0
    adafruit/Adafruit TCA8418@^1.0.2
    adafruit/RTClib@^2.1.4
    olikraus/U8g2@^2.36.4
    https://github.com/bildr-org/MPR121
    ; Currently using a fork of the library
    ; zinggjm/GxEPD2@^1.6.3
    https://github.com/ashtf8/GxEPD2_Editable_useFastFullUpdate

; This should be the closest to the original
[env:devkit]
platform = espressif32
board = lolin_s3
framework = arduino

; TODO: add definition for PDA V2
[env:pdaV2]
platform = espressif32
board = lolin_s3
framework = arduino